### ISSUE TITLE
Creation of initial seafile admin fails

### ISSUE THREAD

**Issue by UnrealKazu** [stonemaster/docker-seafile-server#5]
When spinning up a fresh container, I receive the following error halfway through the initial setup script:

```bash
seafile  | Starting seahub...
seafile  | + echo 'Starting seahub...'
seafile  | + ./seahub.sh start-fastcgi
seafile  |
seafile  | LANG is not set in ENV, set to en_US.UTF-8
seafile  | LC_ALL is not set in ENV, set to en_US.UTF-8
seafile  | ./seahub.sh: line 209: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
seafile  | Starting seahub (fastcgi) at 127.0.0.1:8000 ...
seafile  |
seafile  | Error happened during creating seafile admin.
```

This is a snippet from the logs. The container starts fine, and I can actually get to the login page, but since the admin account has not been created, I cannot log in.

I've been digging through the Seafile codebase to find out where this pops up, and it looks like the `check_init_admin.py` file is where the exception is thrown, which is called by `seahub.sh`.

I'm creating the container using the following `docker-compose`:
```
version: '3'

services:
  cloud:
    container_name: seafile
    image: stonemaster/docker-seafile-server
    volumes:
      - /containers/Seafile:/data
    expose:
      - "80"
    environment:
      - SEAFILE_EXTERNAL_PORT=80
      - SEAFILE_HOSTNAME=localhost
      - SEAFILE_SERVER_NAME=test
      - SEAFILE_ADMIN_EMAIL=actual@email.com
      - SEAFILE_ADMIN_PASSWORD=password

networks:
  default:
    external:
      name: nginx-proxy
```

There is another reverse proxy in front of this container. I'm assuming this won't interfere with the admin creation process, but I'm still mentioning it just in case.

By the way: thanks for creating this. It is much, much better than the strange dockerfile wrapper script presented by the Seafile devs themselves.
